#Author:harshal_509
for _ in range(int(input())):
    s=input()
    k,n,m=map(int,input().split())
    a=list(map(int,input().split()))
    b=list(map(int,input().split()))
    ans=[]
    i=0
    j=0
    flag=1
    while(i<n and j<m):
        if(a[i]==0):
            ans.append(a[i])
            i+=1
            k+=1
        elif(b[j]==0):
            ans.append(b[j])
            j+=1
            k+=1
        elif(a[i]<b[j]):
            if(a[i]>k):
                flag=0
                break
            else:
                ans.append(a[i])
                i+=1
        else:
            if(b[j]>k):
                flag=0
                break
            else:
                ans.append(b[j])
                j+=1
    if(i==n):
        while(j<m):
            if(b[j]>k):
                flag=0
                break
            else:
                if(b[j]==0):
                    k+=1
                ans.append(b[j])
                j+=1
    else:
        while(i<n):
            if(a[i]>k):
                flag=0
                break
            else:
                ans.append(a[i])
                if(a[i]==0):
                    k+=1
                i+=1
    if(flag):
        print(*ans)
    else:
        print("-1")