from collections import Counter
for _ in range(int(input())):
    n=int(input())
    s=input()
    i=0
    j=n-1
    ans=0
    flag=0
    ans1=0
    while(i<j):
        if(flag==1):
            break
        elif(s[i]!=s[j]):
            ans=1
            ans1=10000000000000
            p=s[i]
            q=s[j]
            c1=0
            c2=0
            x=i+1
            y=j
            while(x<y):
                if(s[x]==s[y]):
                    x+=1
                    y-=1
                elif(s[x]!=s[y] and s[x]!=p and s[y]!=p):
                    c1=-1
                    break
                else:
                    ans+=1
                    if(s[x]==p):
                        x+=1
                    else:
                        y-=1
            if(c1!=-1):
                ans1=ans
            x=i
            y=j-1
            ans=1
            while(x<y):
                if(s[x]==s[y]):
                    x+=1
                    y-=1
                elif(s[x]!=s[y] and s[x]!=q and s[y]!=q):
                    c2=-1
                    break
                else:
                    ans+=1
                    if(s[x]==q):
                        x+=1
                    else:
                        y-=1
            if(c1==-1 and c2==-1):
                flag=1
            if(c2!=-1):
                ans1=min(ans1,ans)
            break
        i+=1
        j-=1
    if(flag):
        print(-1)
    else:
        print(ans1)